  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan

    env:
      TF_WORKING_DIR: ./terraform
      AWS_REGION: us-west-2

    steps:
      - name: Wait for Manual Approval
        uses: peter-evans/manual-approval@v2
        with:
          timeout_minutes: 1440
          instructions: 'Please review the Terraform plan above and approve to apply changes.'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan.binary
