name: Terraform CI/CD with Manual Approval

on:
  push:
    branches:
      - main

env:
  TF_WORKING_DIR: . # Adjust this if your code is in a different folder
  AWS_REGION: us-west-2        # Change this to your region

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan.binary

      - name: Show Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -no-color tfplan.binary

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan.binary

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan

    steps:
      - name: Wait for Manual Approval
        uses: peter-evans/manual-approval@v1
        with:
          timeout-minutes: 1440
          instructions: 'Review the Terraform plan and approve to apply changes.'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
